// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjpkhpphbtudmewosicc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqcGtocHBoYnR1ZG1ld29zaWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQxMjcsImV4cCI6MjA2NzExMDEyN30.T5hbOlpJwLgHL2-FspXC8yCXw-JO8O6uNjxe00UJSZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});